---
groups_to_create:
  - name: docker
  - name: wheel
  - name: sudo

users:
  - username: chasinglogic
    name: Mathew Robinson
    home: /home/chasinglogic
    update_password: on_create
    groups:
      - sudo
      - wheel
      - docker

zsh_users: "{{ users }}"

dconf_settings:
  - name: Set CAPSLOCK as Ctrl and Disable ALTGR on UK keyboards
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['ctrl:nocaps', 'lv3:ralt_alt']"

deb_package_specs: []
rpm_package_specs: []
generic_package_specs: []

rpm_packages:
  # Development tooling for GCC C/C++
  - autoconf
  - automake
  - clang-tools-extra
  - gcc
  - gcc-c++
  - llvm

  # Virtualization software
  - gnome-boxes

  # Stuff I wish was included by default on everything
  - gnome-calendar
  - gnome-weather
  - gnome-clocks
  - geary

  # System monitor
  - htop

  # CCache, Ninja, and Meson
  - ccache
  - meson
  - ninja-build

  # Introspection
  - strace
  - ltrace
  - valgrind

  # TAGs
  - cscope
  - ctags

  # Misc tools
  - curl
  - git
  - indent
  - jq
  - libtool
  - tmux

  # Documentation
  - pandoc

  # Lint / Correctness
  - yamllint

  # Neovim / Tmux system clipboard support
  - xclip

  # PyPI upload tool
  - twine

  # Spell checker
  - aspell
  - aspell-en

  # Text editor
  - neovim

  # Kubernetes
  - kubectl

  # Code tools
  - ripgrep
  - perf

  # Writing tools
  - proselint

  # Misc tools and libs
  - libtool
  - python3-ansible-lint
  - python3-libselinux
  - python3-psutil

  # Postgres
  - postgresql
  - postgresql-devel

  # Ruby
  - ruby-devel

  # Python
  - python
  - python-devel
  - python-pip
  - python3
  - python3-devel
  - python3-pip
  - python3-pylint
