---
groups_to_create:
  - name: docker
  - name: wheel
  - name: sudo

users:
  - username: chasinglogic
    name: Mathew Robinson
    home: /home/chasinglogic
    update_password: on_create
    groups:
      - sudo
      - wheel
      - docker
      - libvirt
      - kvm

zsh_users: "{{ users }}"

dconf_settings:
  - name: Set CAPSLOCK as Ctrl and Disable ALTGR on UK keyboards
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['ctrl:nocaps', 'lv3:ralt_alt']"

deb_package_specs: []
rpm_package_specs: []

deb_packages:
  - bind9-utils
  - iputils-ping
  - traceroute

rpm_packages:
  - python3-devel
  - bind-utils
  - iputils
  - neovim

generic_package_specs: []

generic_packages:
  # Virtualization software
  - gnome-boxes
  - virt-manager
  - podman

  # Stuff I wish was included by default on everything
  - gnome-calendar
  - gnome-weather
  - gnome-clocks

  # System monitor
  - htop

  # Introspection
  - strace
  - ltrace
  - valgrind

  # Misc tools
  - curl
  - indent
  - libtool
  - ripgrep
  - fd-find
  - tmux

  # Neovim / Tmux system clipboard support
  - wl-clipboard

  # PyPI upload tool
  - twine

  # Spell checker
  - aspell
  - aspell-en

  # Programming tools
  - golang-go
