---
groups_to_create:
  - name: docker
  - name: wheel
  - name: sudo

users:
  - username: chasinglogic
    name: Mathew Robinson
    home: /home/chasinglogic
    update_password: on_create
    groups:
      - sudo
      - wheel
      - docker

zsh_users: "{{ users }}"

dconf_settings:
  - name: Set CAPSLOCK as Ctrl and Disable ALTGR on UK keyboards
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['ctrl:nocaps', 'lv3:ralt_alt']"

deb_package_specs: []
rpm_package_specs: []
generic_package_specs: []

rpm_packages:
  # Development tooling for GCC C/C++
  - autoconf
  - automake
  - gcc
  - llvm

  # Virtualization software
  - gnome-boxes

  # System monitor
  - htop

  # CCache, Ninja, and Meson
  - ccache
  - meson
  - ninja-build

  # Introspection
  - strace
  - ltrace
  - valgrind

  # TAGs
  - cscope
  - ctags

  # Misc tools
  - git
  - curl
  - indent
  - jq
  - libtool
  - tmux

  # Documentation
  - pandoc

  # Lint / Correctness
  - yamllint

  # Neovim / Tmux system clipboard support
  - xclip

  # PyPI upload tool
  - twine

  # Spell checker
  - aspell
  - aspell-en

  # Text editor
  - neovim

  # C++ Compiler
  - gcc-c++
  - clang-tools-extra

  # Icecream
  - icecream
  - icemon

  # Misc tools
  - perf
  - the_silver_searcher
  - python3-libselinux
  - python3-ansible-lint
  - maildir-utils
  - proselint
  - libtool

  # MPB dev libs
  - libxml2-devel
  - libxslt-devel
  - python2-devel
  - mysql

  # MongoDB Development Libraries
  - flex
  - openssl-devel
  - net-snmp-devel
  - cyrus-sasl-devel
  - libcurl-devel
  - openldap-devel
  - krb5-devel

  # Postgres
  - postgresql
  - postgresql-devel

  # Ruby
  - ruby-devel

  # Python
  - python
  - python-devel
  - python-pip
  - python3
  - python3-devel
  - python3-pip
  - python3-pylint
  
  # Emacs devel libraries
  - gtk3-devel
  - giflib-devel 
  - libtiff-devel 
  - libjpeg-devel
  - libXpm-devel 
  - gnutls-devel
  - ncurses-devel
  - jansson-devel
  - texinfo
