---
- hosts: workstation
  roles:
    - chasinglogic.os_packages
    - chasinglogic.ansible_users
    - andrewrothstein.terraform
    - chasinglogic.linux_power_saving
    - chasinglogic.dconf_settings
    - zsh
    - chasinglogic.updates
  tasks:
    - name: Install google cloud sdk repository
      become: true
      become_user: root
      yum_repository:
        name: google-cloud-sdk
        description: Google Cloud SDK
        baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64 
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    - name: Install Google Cloud SDK
      become: true
      become_user: root
      dnf:
        name:
          - kubectl
          - google-cloud-sdk 
