---
- src: andrewrothstein.terraform
  version: v2.2.32
- src: andrewrothstein.packer
  version: v2.1.13
- src: chasinglogic.os_packages
  version: 1.0.1

- src: chasinglogic.ansible_users
- src: chasinglogic.dconf_settings
- src: chasinglogic.linux_power_saving
- src: chasinglogic.podman
