- name: Install homebrew packages
  community.general.homebrew:
    state: present
    name:
        # Formula
        - ansible
        - atuin
        - awk
        - awscli
        - bash
        - bash-completion@2
        - checkov
        - circleci
        - composer
        - coreutils
        - curl
        - emacs-plus@29
        - gnu-sed
        - gnu-tar
        - gnutls
        - go
        - goreleaser
        - graphviz
        - grep
        - helm
        - htop
        - jq
        - just
        - kubernetes-cli
        - mysql
        - mysql-client
        - neovim
        - openssl@1.1
        - openssl@3
        - podman
        - pulumi
        - pulumictl
        - python@3.11
        - ripgrep
        - shellcheck
        - sqlite
        - tmux
        - tree-sitter
        - watch
        - wrk
        - yq
        # Casks
        - hombrew/cask/docker
        - hombrew/cask/firefox
        - hombrew/cask/font-dejavu
        - hombrew/cask/iterm2
        - hombrew/cask/notion
        - hombrew/cask/podman-desktop
        - hombrew/cask/postman
        - hombrew/cask/pycharm
        - hombrew/cask/rectangle
        - hombrew/cask/spotify
 
